---
title: "Publications"
format: html
editor: visual
bibliography: all_references.bib 
csl: apa.csl
link-citations: true
theme: minty 
---

[\<- Back to home page](http://clementinecttn.github.io/)

## Most recent {#publi-recent}

- [@san_millan_economic_2025]: In this paper, we compute income inequality and residential segregation annually in all urban areas of the Netherlands from 2011 to 2022 and show they have remained stable or decreased in most cities. We analyse how income is distributed by percentile of the income distribution, how each percentile is segregated and at which geographical scale segregation occurs in different cities. Urban areas vary strongly: more unequal urban areas tend to be more segregated, but the same segregation levels can coexist with diverse inequality metrics.

- [@cottineau2025evaluer]: In this chapter, we reflect on the specificity of peer-review for data papers, with the experience gathered from Cybergeo, a scientific open access journal publishing geography articles, where a section dedicated to data papers was created in 2017.

- [@roxburg2025outlining]: In this piece, we propose a list of features that would greatly enhance population synthesis methods from the perspective of agent-based modelling. These include, but are not limited to: the attributes of agents, their location in space, the ways they make decisions and their behavioural dynamics. In the real-world, these aspects of everyday human life can be deeply interconnected, with these associations being highly consequential in shaping outcomes. Initialising synthetic populations in ways that fail to respect these covariances can therefore compromise model efficacy, potentially leading to biased and inaccurate simulation outcomes.

- [@cottineau2024SLRIneq]: In this working paper, I examine how economic inequality and economic segregation are connected theoretically and empirically. I do so by systematically analyzing the direction of causality, causal pathways and temporal relationship reflected by a multidisciplinary and multilingual literature. I conclude that variations in economic segregation follow differences in economic inequality in the short term and that reverse causality is more probable in the longer term, that the housing market is the most frequent mediator between economic inequality and economic segregation and that the current scholarship on the topic is far from comparable, although compatible definitions and measurements of inequality and segregation are rising.

- [@janssen2024spatial]: In this article, we analyse the spillover effects of contemporary state-led gentrification in Rotterdam. More specifically, we analyse the changing socioeconomic characteristics of in-movers and the changing origin locations of residential moves, concluding that Rotterdam increasingly attracts middle- to high-income households from other core cities in the Netherlands while intra-urban moves by economically vulnerable residents are declining, especially toward and within gentrifying neighborhoods.

## Peer reviewed articles {#publi-articles}

-   on Economic Inequality, residential segregation and urban inequality: [@cottineau2019defining] [@cottineau2019mobile] [@schneider2019decentralisation] [@janssen2023gentrification] [@janssen2024spatial] [@san_millan_economic_2025]
-   on Literature reviews and the history of urban studies: [@cottineau2017metazipf] [@raimbault2021empowering] [@cottineau2022analyses] [@janssen2023gentrification] [@achter2024conduct] [@cottineau2024unforeseen] 
-   on Urban scaling laws and systems of cities: [@pumain2015multilevel] [@cottineau2017diverse] [@cura2017old] [@cottineau2017metazipf] [@finance2019absent] [@cottineau2019defining]
-   on Agent-based modelling: [@cottineau2015modular] [@cottineau2015growing] [@cherel2015beyond] [@raimbault2019space] [@achter2024conduct]
-   on Urbanisation in the post-Soviet Space: [@cottineau2011processus] [@cottineau2012intermediate] [@cottineau2015modular] [@cottineau2015growing] [@cottineau2016multilevel] [@cottineau2017peut]
-   on the Geography of production: [@cottineau2019defining] [@cottineau2020nested] [@brochard2022negociation] [@askenazy2024geography]
-   on Urban policy: [@schneider2019decentralisation] [@cottineau2024unforeseen]

## Books {#publi-books}

-   Edited book on inequalities in geographical space: [@cottineau2022inequalities]

-   Edited book on cities and inequalities: [@cottineau2022cities]

## Book chapters {#publi-book-chapters}
-   In C. Kosmopoulos & J. Schöpfel (dir.), 2025, *Publier, partager, réutiliser les données de la recherche: les data papers et leurs enjeux*: [@cottineau2025evaluer]
-   In R. Harris, A. Heppenstall, & L. J. Wolf (Eds.), 2024, *A research agenda for spatial analysis*: [@cottineau2024generative]
-   In C. Cottineau & J. Vallée (Eds.), 2022, *Inequalities in geographical space*: [@cottineau2022introduction] [@cottineau2022modeling]
-   In C. Cottineau & D. Pumain (Eds.), 2022, *Cities at the heart of inequalities*: [@cottineau2022major] [@cottineau2022inequalitiesbetweencities]
-   In D. Pumain (Ed.), 2020, *Theories and models of urbanization: Geography, economics and computing sciences*: [@baffi2020emerging]
-   In D. Pumain (Ed.), 2019, *Geographical modeling: Cities and territories*: [@cottineau2019incremental]
-   In D. Pumain, C. Rozenblat, & E. Velasquez (Eds.), 2018, *International and transnational perspectives on urban systems*: [@cottineau2018russian]

## Other {#publi-other}

-   My PhD Dissertation: [@cottineau2014evolution]
-   Non-peer-reviewed articles: [@drouzhinin2010identifikatsia] [@covprehension2020understanding] [@roxburg2025outlining]
-   Working Papers: [@cottineau2016jean] [@barner2017multiscale] [@cottineau2018agent] [@SLRbanismWorkingPaper] [@cottineau2024SLRIneq]
-   Editorial: [@sarkar2024spatial]
-   Workshop repository: [@Forgaci_Geospatial_Data_Carpentry]
-   Book reviews: [@cottineau2011baron] [@cottineau2014piketty] [@cottineau2017west] [@cottineau2020lahire]
-   Report: [@avila2011mapping]
-   Commentaries: [@cottineau2024accommodating]

## Full list {#publi-list}

::: {#refs}
:::

[Back to home page](http://clementinecttn.github.io/)
