---
title: "Research"
format: html
editor: visual
bibliography: research_references.bib 
csl: apa.csl
link-citations: true
theme: minty 
---

[\<- Back to home page](http://clementinecttn.github.io/)

I am an urban geographer specialised in the economic, social and spatial aspects of inequality in cities. My [on-going research](http://clementinecttn.github.io/Website/research#research-ongoing) project SEGUE deals with the identification and modeling of the combination of economic, geographic, sociological and demographical drivers of urban economic segregation. I have a strong [research interest](http://clementinecttn.github.io/Website/research#interest) in analytical urban models and systematic literature reviews. [Past projects](http://clementinecttn.github.io/Website/research#research-previous) involves research on urban scaling laws and urbanisartion in the post-Soviet space.

### Research positions

```{r, echo=FALSE}
library(leaflet)
library(htmltools)

locations <- read.csv(textConnection(
"Name,Lat,Long
2020-... Assistant professor in Urban Studies (TU Delft BK - Urbanism), 52.0055648,4.3681619
2014-2017 Research associate (UCL-CASA),51.5219617,-0.1384865
2018-... Research associate (CNRS-CMH) | 2011-2014 PhD Candidate in Urban Geography (U. Paris 1 Panthéon Sorbonne),48.8447567,2.3399484

"
))


leaflet(locations) %>% 
  setView(4.3681619, 52.0055648, 3) %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addCircleMarkers(~Long, ~Lat, popup = ~htmlEscape(Name),
    radius = 10,
    color = "#E30B5C",
    stroke = FALSE, fillOpacity = 0.5) %>%
 addCircleMarkers(
      lng = 39.037904, lat = 47.2599601,
    label = "Research Assistant (U. of Southern Russia)",
    radius = 7,
    color = "#85001D",
    stroke = FALSE, fillOpacity = 0.5)


```

## On-going project {#research-ongoing}

My main line of research revolves around the integration of multiple mechanisms of economic segregation in analytical models of cities. This is the core of my [ERC Starting Grant SEGUE](erc-segue.nl), which started in September 2022 and will run until August 2027.

The knowledge gaps related to the evolution of urban economic segregation in multiple cities can be reduced first, by accounting for the economic composition and inequality dynamics of the entire system (nationally), and second, by accounting for individual and family trajectories of economic mobility, through a focus on demographic factors and wealth transmission. Although these national and individual processes are well documented empirically and theoretically, we do not know where they materialise (between and within cities) and how they interact with other spatial processes.

The innovative ambition of **SEGUE** is to consider, for the first time, the analysis of processes of (re-)production of inequality which affect the spatial distribution of economic groups in cities through the construction of a modular agent-based model, calibrated on exhaustive longitudinal and geolocated empirical microdata from the Netherlands.

My ultimate objective is to use this model to assess and compare different policy strategies (typical, past and current) to reduce urban inequality and economic segregation in a cost-effective and time-saving way: within the virtual laboratory of a simulation (in silico). This objective can only be fulfilled if the relevant drivers of urban economic segregation are accounted for jointly.

## Current research Topics {#research-interest}

### Analytical urban models of urban inequality {#research-models}

In my research, I use analytical models to integrate and archive multidisciplinary knowledge on cities and to highlight patterns and stylised facts which are not currently well understood and explained. Following epistemological developments in analytical sociology [@hedstrom2005dissecting], I defend the idea that descriptive models (e.g. statistical regression) and generative models (e.g. agent-based models - ABMs) can be used in combination to produce better and more robust causal explanations of collective urban phenomena such as economic segregation.

To operationalise this idea, I review existing knowledge and relevant models [@cottineau2024unforeseen], combine them into modular infrastructure of agent-based modelling [@cottineau2015modular], and use empirical microdata to test hypotheses [@cottineau2020nested] [@askenazy2024geography].

### Systematic literatre reviews {#research-review}

Systematic literature reviews have been a method of choice that I have used, developed and argued for in urban studies and agent-based modelling over the past 5 years [@cottineau2017metazipf] [@cottineau2022analyses] [@janssen2023gentrification] [@cottineau2024generative] because they are particularly suited to multidisciplinary research fields (where it is easy to miss literature in a different discipline because a given concept or process is known and studied under a different term) and when we are interested in reviewing emerging methods such as ABMs (where most models are built from scratch for a single use, hindering cumulative knowledge and the incremental improvement of models). Using this experience, I now work on improving approaches and sharing open toolboxes available for urban researchers and agent-based modellers to conduct systematic reviews [@achter2024conduct] [@SLRbanismWorkingPaper].

## Previous projects {#research-previous}

-   In the past, I have studied urban scaling laws and how the delineation of cities (for instance the choice of density and commuting thresholds) affected their estimation [@cottineau2017diverse] [@finance2019absent] [@cottineau2019mobile].

-   As part of my PhD research, I looked into the specificity of urbanisation in the post-Soviet space, using general models as baseline [@cottineau2011processus] [@cottineau2012intermediate] [@cottineau2015modular] [@cottineau2017peut] and considering urban shrinkage [@cottineau2016multilevel] [@cottineau2018russian].

## References

::: {#refs}
:::

[Back to home page](http://clementinecttn.github.io/)
